jobs:
- job: windows_build
  displayName: 'Build for Windows'
  pool:
    vmImage: 'VS2017-Win2016'
  strategy:
    matrix:
      x64:
        TARGET_ARCH: x64
      x86:
        TARGET_ARCH: x86
  steps:
  - template: azure-pipelines-template.yml

- job: macos_build
  displayName: 'Build for macOS'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      x64:
        TARGET_ARCH: x64
  steps:
  - template: azure-pipelines-template.yml
