pool:
  vmImage: 'VS2017-Win2016'

strategy:
  matrix:
    x64:
      TARGET_ARCH: x64
    x86:
      TARGET_ARCH: x86

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: 10.x

- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'
    architecture: 'x64'

- script: node build.js %TARGET_ARCH%
  displayName: Build
