jobs:
- job: windows_build
  displayName: 'Build for Windows'
  pool:
    vmImage: 'VS2017-Win2016'
  strategy:
    matrix:
      x64:
        TARGET_ARCH: x64
      x86:
        TARGET_ARCH: x86
  timeoutInMinutes: 120
  cancelTimeoutInMinutes: 120
  steps:
  - template: azure-pipelines-template.yml

- job: macos_build
  displayName: 'Build for macOS'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      x64:
        TARGET_ARCH: x64
  steps:
  - template: azure-pipelines-template.yml

- job: linux_build
  displayName: 'Build for Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      x64:
        TARGET_ARCH: x64
      x86:
        TARGET_ARCH: x86
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y libgtk-3-dev
  - script: |
      sudo dpkg --add-architecture i386
      sudo apt-get update
      sudo apt-get install -y gcc-multilib g++-multilib
    condition: eq(variables['TARGET_ARCH'], 'x86')
    displayName: Install x86 dependencies
  - template: azure-pipelines-template.yml
