on: push
#   release:
#     types: [created]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-16.04]
        include:
          - os: ubuntu-16.04
            asset_dir: "node/out/Release/linux/"
            asset_name: "linux-x64.zip"
          # - os: windows-latest
          #     asset_dir: node/out/Release/win32/
          #     asset_name: win32-x64.zip
          # - os: macos-latest
          #     asset_dir: node/out/Release/darwin/
          #     asset_name: darwin-x64.zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Install Qt
        uses: jurplel/install-qt-action@v1
        with:
          version: 5.13.1
      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-16.04'
        run: sudo apt install libgtk-3-dev patchelf
      - name: Build Qode
        env:
          SYNC_GIT_SUBMODULE: true
          QT_INSTALL_DIR: ${{job.container.env.Qt5Dir}}
        run: node build.js
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          path: ${{matrix.asset_dir}}
          filename: "release.zip"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release.zip
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
