on: push
#   release:
#     types: [created]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest]
        include:
          - os: ubuntu-16.04
            artifact_name: mything
            asset_name: linux-x64.zip
#         - os: windows-latest
#             artifact_name: mything.exe
#             asset_name: win32-x64.zip
          - os: macos-latest
            artifact_name: mything
            asset_name: darwin-x64.zip
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        version: 12
    - name: Install Qt
      uses: jurplel/install-qt-action@v1
      with: 
        version: 5.13.1
    - name: Build Qode
      run: QT_INSTALL_DIR=$Qt5_Dir node build.js
    
#     - name: Upload binaries to release
#       uses: svenstaro/upload-release-action@v1-release
#       with:
#         repo_token: ${{ secrets.GITHUB_TOKEN }}
#         file: target/release/${{ matrix.artifact_name }}
#         asset_name: ${{ matrix.asset_name }}
#         tag: ${{ github.ref }}
